name: buf
on:
  push:
    paths:
      - 'proto/**'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.6.0
      - uses: bufbuild/buf-lint-action@v1.0.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
  breaking:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.6.0
      - uses: bufbuild/buf-breaking-action@v1.1.1
        with:
          against: 'https://github.com/bufbuild/connect-demo.git#branch=main'
  push:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - breaking
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.6.0
      - uses: bufbuild/buf-push-action@v1.0.1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
